export const REQUEST_PHOTOS = 'REQUEST_PHOTOS'
export const SUCCESS_PHOTOS = 'SUCCESS_PHOTOS'
export const ERROR_PHOTOS = 'ERROR_PHOTOS'

export const SELECT_PHOTO = 'SELECT_PHOTO'

export const REQUEST_PHOTO_COMMENT = 'REQUEST_PHOTO_COMMENT'
export const SUCCESS_PHOTO_COMMENT = 'SUCCESS_PHOTO_COMMENT'
export const ERROR_PHOTO_COMMENT = 'ERROR_PHOTO_COMMENT'

export const REQUEST_SEND_PHOTO_COMMENT = 'REQUEST_SEND_PHOTO_COMMENT'
export const SUCCESS_SEND_PHOTO_COMMENT = 'SUCCESS_SEND_PHOTO_COMMENT'
export const ERROR_SEND_PHOTO_COMMENT = 'ERROR_SEND_PHOTO_COMMENT'

export const optionsDate = {
  day: 'numeric',
  month: 'numeric',
  year: 'numeric',
}
